# Generated by Django 4.0.4 on 2022-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillionCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=2500)),
            ],
            options={
                'verbose_name_plural': 'MillionCalculator',
            },
        ),
    ]
