# Generated by Django 4.0.4 on 2022-09-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0012_whatisnextfibonaccicalculator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='decimalplacevalue',
            new_name='decimalplacevalueCalculator',
        ),
        migrations.AlterModelOptions(
            name='decimalplacevaluecalculator',
            options={'verbose_name_plural': 'decimalplacevalueCalculator'},
        ),
    ]
