# Generated by Django 4.0.4 on 2022-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0051_independenteventscalculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='aot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=50)),
                ('b', models.CharField(max_length=5)),
                ('c', models.CharField(max_length=5)),
                ('steps', models.TextField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='distanceBetweenPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point1', models.CharField(max_length=50)),
                ('point2', models.CharField(max_length=50)),
                ('steps', models.TextField()),
                ('d', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='interceptForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqn', models.CharField(max_length=50)),
                ('cox', models.CharField(max_length=5)),
                ('coy', models.CharField(max_length=5)),
                ('cons', models.CharField(max_length=5)),
                ('slope', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='maxAreaRectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perim', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('halfperim', models.CharField(max_length=10)),
                ('quatperim', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='poly_root_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputEnter', models.CharField(max_length=250)),
                ('detailStep', models.TextField()),
                ('finalAnswer', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('solutionTitle', models.CharField(max_length=250)),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'poly_root_db',
            },
        ),
    ]
