import imp
from django.contrib import admin
from .models import *
#from .models import MillionCalculator
# Register your models here.
admin.site.register(percenttToDecimalCalculator)
admin.site.register(decimalToPercentageCalculator)
admin.site.register(moduloCalculator)
admin.site.register(dividedByWhatCalculator)
admin.site.register(negativeDividedCalculator)
admin.site.register(millionzerosCalculator)
admin.site.register(billionzerosCalculator)
admin.site.register(crorezerosCalculator)
admin.site.register(croreinnumberCalculator)
admin.site.register(decimaltobinaryCalculator)
admin.site.register(decimalplacevalueCalculator)
admin.site.register(addingfractionCalculator)
admin.site.register(multiplyingfractionCalculator)
admin.site.register(dividingfractionCalculator)
admin.site.register(mixedfractionCalculator)
admin.site.register(threedigitnumberCalculator)
admin.site.register(fourdigitnumberCalculator) 
admin.site.register(whatisnextfibonacciCalculator) 
admin.site.register(howdoyouaddpercenttonumberCalculator) 
admin.site.register(greatestcommondivisorCalculator)
admin.site.register(onedecimalplaceCalculator)
admin.site.register(percentofwhatnumberCalculator)
admin.site.register(rationalnumberCalculator)
admin.site.register(whattwonumberadduptoCalculator)
admin.site.register(sequentialpercentageCalculator)
admin.site.register(fractiondividedbynumberCalculator)
admin.site.register(lakhzerosCalculator)
admin.site.register(percentasdecimalCalculator)
admin.site.register(whatpercentCalculator)
admin.site.register(xtimesxCalculator)
admin.site.register(squarerootnumberCalculator)
admin.site.register(squaremetertofeetCalculator)
admin.site.register(squareinchtofeetCalculator)
admin.site.register(secondpowerCalculator)
admin.site.register(thirdpowerCalculator)
admin.site.register(squaredCalculator)
admin.site.register(minutesofhourpercentCalculator)
admin.site.register(percenttopermileCalculator)
admin.site.register(scientificnotationCalculator)
admin.site.register(cubiccentimeterstocubicmetersCalculator)
admin.site.register(sumofintegerCalculator)
admin.site.register(randomnumberbetweenCalculator)
admin.site.register(squarerootoffractionCalculator)
admin.site.register(numberpluspercentCalculator)
admin.site.register(numberminuspercentCalculator)
admin.site.register(atsequence)
admin.site.register(sumofgeometricsequenceCalculator)
admin.site.register(sumofarithmeticsequenceCalculator)
admin.site.register(arithmeticsequencetermCalculator)
admin.site.register(geometricsequencetermCalculator)
admin.site.register(rectangulardimensionCalculator)
admin.site.register(areaOfTheParallelogramCalculator)
admin.site.register(differentialequationCalculator)
admin.site.register(fractionofadayinhourCalculator)
admin.site.register(coordinatesh)
admin.site.register(remainderofequationCalculator)
admin.site.register(HorizontalTangent)



